# .github/workflows/deploy-apply.yml
name: Terraform Apply

on:
  workflow_call:
    inputs:
      image_version:
        required: true
        type: string

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        working-directory: Terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: Terraform
        run: terraform apply -auto-approve -var="image_version=${{ inputs.image_version }}"
